// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBZr5BnHeA-4eLzEacmHC4M-tKnpXCA-T4",
    authDomain: "bbb-app-d4b41.firebaseapp.com",
    projectId: "bbb-app-d4b41",
    storageBucket: "bbb-app-d4b41.appspot.com",
    messagingSenderId: "693919444814",
    appId: "1:693919444814:web:fa9035568f3e1067f8f81f",
    measurementId: "G-Q6ZCD3369N"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6BrEdFWM91hhDdEJj0CMH6bA_FZaWc1k',
    appId: '1:693919444814:android:8edebf6ac1be3db7f8f81f',
    messagingSenderId: '693919444814',
    projectId: 'bbb-app-d4b41',
    storageBucket: 'bbb-app-d4b41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo09dl6-mqvgjqjza5c9AzqwGFPPWmQOE',
    appId: '1:693919444814:ios:abac2dd8cba4effdf8f81f',
    messagingSenderId: '693919444814',
    projectId: 'bbb-app-d4b41',
    storageBucket: 'bbb-app-d4b41.appspot.com',
    iosBundleId: 'com.perceptively.bbb',
  );
}
